-- Run this in Supabase Dashboard -> SQL Editor -> New query -> Run.
-- Adds overall ratings to free_agents (column didn't exist before) and
-- applies them for every name that matches. Source file:
-- GMCHL_Free_Agency_Updated.xlsx -- it covers 123 names, far more than the
-- ~19 recognizable free agents this app actually tracks (the rest are deep
-- AHL/ECHL names, e.g. single-initial entries like "K. Bindulis"), so this
-- only touches whoever's already in our free_agents pool; the extra names
-- harmlessly match zero rows. Goalies aren't in this sheet at all (Reimer,
-- Mrazek stay null), and a few names here (Mike Reilly, Tyson Jost, Alex
-- Nylander) are already signed or on a PTO and no longer in our pool at
-- all, so they no-op too -- expected, not a bug.

alter table free_agents add column if not exists overall int;

with fa_ratings (player_name, ovr) as (
  values
    ('John Klingberg', 83),
    ('Nick Blankenburg', 83),
    ('Patrik Laine', 83),
    ('Vladimir Tarasenko', 83),
    ('David Perron', 82),
    ('Evander Kane', 82),
    ('Michael Bunting', 82),
    ('Reilly Smith', 82),
    ('Carson Soucy', 81),
    ('Gustav Nyquist', 81),
    ('Jonathan Drouin', 81),
    ('Logan Stanley', 81),
    ('Matt Grzelcyk', 81),
    ('Nick Leddy', 81),
    ('Philipp Kurashev', 81),
    ('Adam Boqvist', 80),
    ('Adam Henrique', 80),
    ('Jake Bean', 80),
    ('James van Riemsdyk', 80),
    ('Jeff Petry', 80),
    ('Luke Glendening', 80),
    ('Luke Kunin', 80),
    ('Mike Reilly', 80),
    ('Nathan Bastian', 80),
    ('Ryan Suter', 80),
    ('Adam Erne', 79),
    ('Ben Hutton', 79),
    ('Brandon Saad', 79),
    ('Brandon Smith', 79),
    ('Curtis Lazar', 79),
    ('David Quenneville', 79),
    ('Evgeny Dadonov', 79),
    ('Marc-Edouard Vlasic', 79),
    ('Matt Dumba', 79),
    ('Robby Fabbri', 79),
    ('Tanner Pearson', 79),
    ('Travis Boyd', 79),
    ('Travis Hamonic', 79),
    ('Tyson Jost', 79),
    ('Arthur Kaliyev', 76),
    ('Connor Carrick', 76),
    ('K. Dorwart', 76),
    ('Travis Dermott', 76),
    ('Alex Nylander', 75),
    ('Antonio Stranges', 75),
    ('Austin Watson', 75),
    ('Gavin Bayreuther', 75),
    ('Ryan Reaves', 75),
    ('Brandon Gleason', 74),
    ('Brett Ritchie', 74),
    ('Carsen Twarynski', 74),
    ('Chris Criscuolo', 74),
    ('Justin Bailey', 74),
    ('Markus Niemeläinen', 74),
    ('Matt Benning', 74),
    ('Oliver Wahlstrom', 74),
    ('Thomas Bordeleau', 74),
    ('H. Drew', 73),
    ('Jujhar Khaira', 73),
    ('Logan Brown', 73),
    ('Luke Johansen', 73),
    ('P. Dubé', 73),
    ('Paul LaDue', 73),
    ('Philippe Maillet', 73),
    ('Scott Reedy', 73),
    ('T. Barron', 73),
    ('Will Butcher', 73),
    ('A. Camara', 71),
    ('Josh Anderson', 71),
    ('Rem Pitlick', 71),
    ('C. Burke', 70),
    ('C. Terry', 70),
    ('D. Osipov', 70),
    ('G. Smith', 70),
    ('J. Foudy', 70),
    ('J. Grubbe', 70),
    ('J. LaBate', 70),
    ('O. Kylington', 70),
    ('A. Vincent', 69),
    ('B. Badcock', 69),
    ('C. Paré', 69),
    ('D. Bancroft', 69),
    ('D. O’Regan', 69),
    ('D. Walcott', 69),
    ('J. Carroll', 69),
    ('J. Gruden', 69),
    ('K. McDonald', 69),
    ('M. Liwiski', 69),
    ('N. Pavychev', 69),
    ('R. O’Rourke', 69),
    ('W. Newpower', 69),
    ('C. Felix', 68),
    ('D. Kambleitz', 68),
    ('J. Jacobs', 68),
    ('K. Washkurak', 68),
    ('L. Svejkovsky', 68),
    ('N. Leivermann', 68),
    ('R. McGregor', 68),
    ('R. McKay', 68),
    ('S. Day', 68),
    ('S. Laberge', 68),
    ('Z. Hayes', 68),
    ('B. Tracey', 67),
    ('J. Doty', 67),
    ('J. Wise', 67),
    ('K. Connauton', 67),
    ('T. Spink', 67),
    ('E. Middendorf', 66),
    ('J. Melnick', 66),
    ('L. Edmonds', 66),
    ('N. Moutrey', 66),
    ('O. Koivula', 66),
    ('P. Guay', 66),
    ('S. Bowers', 66),
    ('C. Brown', 65),
    ('D. Stephens', 65),
    ('G. McPhee', 65),
    ('R. Scarfo', 65),
    ('J. Gaudet', 64),
    ('K. Bindulis', 64),
    ('K. Crnkovic', 64),
    ('P. Granberg', 64),
    ('L. Maver', 63)
)
update free_agents fa
set overall = r.ovr
from fa_ratings r
where fa.name = r.player_name;
